import { ImageSourcePropType } from 'react-native'

export const TILE_IMAGES: Record<string, ImageSourcePropType> = {
  man1: require('../../assets/tiles/man1.png'),
  man2: require('../../assets/tiles/man2.png'),
  man3: require('../../assets/tiles/man3.png'),
  man4: require('../../assets/tiles/man4.png'),
  man5: require('../../assets/tiles/man5.png'),
  man6: require('../../assets/tiles/man6.png'),
  man7: require('../../assets/tiles/man7.png'),
  man8: require('../../assets/tiles/man8.png'),
  man9: require('../../assets/tiles/man9.png'),
  pin1: require('../../assets/tiles/pin1.png'),
  pin2: require('../../assets/tiles/pin2.png'),
  pin3: require('../../assets/tiles/pin3.png'),
  pin4: require('../../assets/tiles/pin4.png'),
  pin5: require('../../assets/tiles/pin5.png'),
  pin6: require('../../assets/tiles/pin6.png'),
  pin7: require('../../assets/tiles/pin7.png'),
  pin8: require('../../assets/tiles/pin8.png'),
  pin9: require('../../assets/tiles/pin9.png'),
  sou1: require('../../assets/tiles/sou1.png'),
  sou2: require('../../assets/tiles/sou2.png'),
  sou3: require('../../assets/tiles/sou3.png'),
  sou4: require('../../assets/tiles/sou4.png'),
  sou5: require('../../assets/tiles/sou5.png'),
  sou6: require('../../assets/tiles/sou6.png'),
  sou7: require('../../assets/tiles/sou7.png'),
  sou8: require('../../assets/tiles/sou8.png'),
  sou9: require('../../assets/tiles/sou9.png'),
  east: require('../../assets/tiles/east.png'),
  south: require('../../assets/tiles/south.png'),
  west: require('../../assets/tiles/west.png'),
  north: require('../../assets/tiles/north.png'),
  haku: require('../../assets/tiles/haku.png'),
  hatsu: require('../../assets/tiles/hatsu.png'),
  chun: require('../../assets/tiles/chun.png'),
}
